spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password: 1234

  batch:
    jdbc:
      initialize-schema: always